name: mlflow_test
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.6.15.2
  - certifi=2022.6.15.2
  - libffi=3.4.2
  - openssl=3.0.5
  - pip=22.2.2
  - python=3.7.12
  - python_abi=3.7
  - setuptools=65.3.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - alembic==1.8.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - colorama==0.4.5
    - cycler==0.11.0
    - databricks-cli==0.17.3
    - docker==5.0.3
    - entrypoints==0.4
    - flask==2.2.2
    - fonttools==4.37.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - greenlet==1.1.3
    - idna==3.4
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - mako==1.2.2
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mlflow==1.28.0
    - numpy==1.21.6
    - oauthlib==3.2.1
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.2.0
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.3
    - protobuf==4.21.6
    - pyjwt==2.4.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pywin32==227
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.28.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==1.4.41
    - sqlparse==0.4.2
    - tabulate==0.8.10
    - threadpoolctl==3.1.0
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - waitress==2.1.2
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - xgboost==1.6.2
    - zipp==3.8.1
